# This is a basic workflow to help you get started with Actions

name: Test Versions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.93lts"] #, "2.92", "2.91", "2.90", "2.83lts", "2.82", "2.81", "2.80", "2.79"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          zip --include '*.py' -r $GITHUB_WORKSPACE/ppl_meshexporter_addon.zip $GITHUB_WORKSPACE
      - name: Install Blender
        run: |
          sudo snap install blender --channel=${{ matrix.blender-version }} --classic
      - name: Test Add-on on version ${{ matrix.blender-version }}
        run: |
          blender -b -P $GITHUB_WORKSPACE/.github/workflows/testblender.py
