# This is a basic workflow to help you get started with Actions

# github.event_name can be used to get the name of the event that started the workflow

name: Test Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Post-test Action (update-readme, release, both, none)"
        required: true
        default: "update-readme"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      addonfiles: ${{ steps.changes.outputs.addonfiles }}
    steps:
      #tbd
  test:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{ needs.changedfiles.outputs.addonfiles }}
    permissions: read-all
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.90", "2.80", "2.79"]
    steps:
      - name: Install Blender
        run: |
          if [ "${{ matrix.blender-version}}" = "2.79" ]; then
            sudo apt-get update
            sudo apt-get install libglu1
          fi
          sudo snap install blender --channel=${{ matrix.blender-version }} --classic
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9.6'
          architecture: 'x64'
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install add-on
        run: |
          mkdir $GITHUB_WORKSPACE/tempmodulefolder
          cp -R $GITHUB_WORKSPACE/ppl_meshexport_addon $GITHUB_WORKSPACE/tempmodulefolder/ppl_meshexport_addon
      - name: Test Add-on on version ${{ matrix.blender-version }}
        run: |
          sudo apt-get install lua5.3
          python $GITHUB_WORKSPACE/.github/workflows/blender_tests/blender_test_wrapper.py
      - name: Upload test results
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: test-results-blender-v${{ matrix.blender-version }}
          path: ${{ github.workspace }}/.github/workflows/blender_tests/test_results.json
          retention-days: 1
#  posttest:
#    runs-on: ubuntu-latest
#    needs: test
      
